version: '3'

services: 
  php-fpm:
    build:
        context: ./php-fpm
    volumes:
        - ../src:/var/www
    depends_on:
        - database

  nginx:
    build:
        context: ./nginx
    volumes:
        - ../src:/var/www
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/sites/:/etc/nginx/sites-available
        - ./nginx/conf.d/:/etc/nginx/conf.d
        - ./nginx/static/:/var/www/static
    depends_on:
      - php-fpm
    ports:
        - "80:80"
        - "443:443"

  database:
    build:
        context: ./database
    environment:
        - MYSQL_DATABASE=mydb
        - MYSQL_USER=myuser
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql
    container_name: database
    ports:
        - "3336:3306"
