name: Publish Docker image
on:
  push:
    branches:        
        - 'main'
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
       - path: "php-fpm"
         repository-name: "testdocker-imagespush"
       - path: "nginx"
         repository-name: "nginx_image"
       - path: "database"
         repository-name: "database_image"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push php-fpm to Docker Hub
        env:
          PATH: ${{ matrix.path }}
          REPOSITORY-NAME: ${{ matrix.repository-name }}
        uses: docker/build-push-action@v2
        with:
          repository: annetkoval/$REPOSITORY-NAME
          context: .
          file: ./docker/$PATH/Dockerfile
          tags: annetkoval/$REPOSITORY-NAME:v6
          push: true
          tag_with_ref: true