on: [push]
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
            registry: eu.gcr.io
            username: _json_key
            password: ${{ secrets.GCR }}
      - name: LS
        run: | 
          ls -la
      - name: Push php-fpm to GCR
        uses: docker/build-push-action@v2
        with:
          registry: eu.gcr.io
          repository: eu.gcr.io/hazel-circlet-303916/testdocker-imagespush
          context: ./docker/php-fpm/
          file: ./docker/php-fpm/Dockerfile
          tags: v6
          push: true
          tag_with_ref: true
