on: [push]
#defaults:
#  run:
#    working-directory: ./docker
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
            registry: eu.gcr.io
            username: _json_key
            password: ${{ secrets.GCR }}
            #project_id: hazel-circlet-303916
            #service_account_key: ${{ secrets.GCR }}
            #export_default_credentials: true

      #- name: Use gcloud CLI
      #  run: gcloud info
      - name: Push php-fpm to GCR
        uses: docker/build-push-action@v2
        with:
          registry: eu.gcr.io
          repository: eu.gcr.io/hazel-circlet-303916/testdocker-imagespush
          context: .
          file: ./docker/php-fpm/Dockerfile
          tags: v6
          push: true
          tag_with_ref: true
