on: [push]
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
       - path: "php-fpm"
         repository-name: "testdocker-imagespush"
       - path: "nginx"
         repository-name: "nginx_image"
       - path: "database"
         repository-name: "database_image"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
            registry: eu.gcr.io
            username: _json_key
            password: ${{ secrets.GCR }}
            #
      - name: Push php-fpm to GCR
        uses: docker/build-push-action@v2
        with:
          registry: eu.gcr.io
          repository: eu.gcr.io/hazel-circlet-303916/${{ matrix.repository-name }}
          context: .
          file: ./docker//${{ matrix.path }}/Dockerfile
          tags: eu.gcr.io/hazel-circlet-303916/${{ matrix.repository-name }}:v6
          push: true
          tag_with_ref: true
